### PR TITLE
Fix vmware-rawdiskCreator bundled in Fusion failed to create disk

### PR DESCRIPTION
**Pull request by yeahdongcn**
This pull request fixes issue https://github.com/bacongravy/macinbox/issues/12

You need to update Fusion to the latest version before testing this.

### Testing done:
```
$ sudo bundle exec macinbox
Password:
• Checking macOS versions...
• Creating image from installer...
  + Creating and attaching wrapper disk image...
  + Creating and attaching a new blank disk image...
  + Installing macOS...
    - installer: 100% done 
  + Configuring the primary user account...
  + Installing the default insecure vagrant ssh key...
  + Enabling password-less sudo...
  + Enabling sshd...
  + Enabling HiDPI resolutions...
  + Saving the image...
• Creating VMDK from image...
  + Copying the image...
  + Attaching the image...
  + Installing the VMware Tools...
  + Setting the KextPolicy to allow loading the VMware kernel extensions...
  + Converting the image to VMDK format...
  + Moving the VMDK to the destination...
• Creating box from VMDK...
  + Assembling the box contents...
  + Moving the box to the destination...
• Installing box...
  + Copying box to /Users/xiaodongy/.vagrant.d/boxes...
    - Installed box: macinbox (vmware_desktop, 10.14)
• Cleaning up...

```

### CODE REVIEW

**Comment by yeahdongcn** [comment]
Please review this once the latest version of Fusion gets released, thanks.

**Comment by yeahdongcn** [comment]
https://my.vmware.com/cn/web/vmware/details?downloadGroup=FUS-1110&productId=798&rPId=33757

**Comment by bacongravy** [comment]
@yeahdongcn Thank you for this PR!  As I wrote in #12, I do have some concerns about implementing the workaround of installing the XPC services.  Did you consider/try having `macinbox` automatically launch VMware Fusion as needed before using `vmware-vdiskmanager`?

I have some ideas for how I could make the service-installation workaround more robust, but I have reservations about investing effort into using VMware Fusion in a way that is not intended and potentially not supported.  For people who cannot have VMware Fusion running when they need to automate disk creation, perhaps `qemu-img` is an acceptable workaround. Do you have a sense for whether this behavior is going to change in `vmware-vdiskmanager` or if this just how it is. Thanks!

**Comment by yeahdongcn** [comment]
Thank you for looking into this @bacongravy ! It is doable to launch VMware Fusion before using `vmware-vdiskmanager` since VMware Fusion will automatically install `com.vmware.MountHelper` and `com.vmware.DiskHelper` for you. But I think this behavior may not be acceptable by all users. That's the reason why I added start/stop privileged helpers code into your script. You can try more robust ways of doing this.

**Comment by bacongravy** [comment]
I addressed this issue with the fix for #12. The tool now checks to see if VMware is running, or if the workaround is enabled, and if not, prints an error.

**Pull request closed without merging**
